# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  imageName: "neutrals-docker"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: test
              projects: "**/*HomeControllerTests/*.csproj"
              ##arguments: "--configuration $(BuildConfiguration)"
              

          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: $(imageName)
              command: build
              dockerfile: "$(Build.SourcesDirectory)/mvc-minitwit/Dockerfile"
              tags: |
                $(tag)

          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: |
                $(dockerHub)
              repository: $(imageName)
              command: push
              tags: |
                $(tag)

          ##Test
