# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  ImageName: 'jokeren9/neutralsminitwit:$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: test
              projects: "**/*HomeControllerTests/*.csproj"
          ##arguments: "--configuration $(BuildConfiguration)"

          - task: Docker@1
            displayName: 'Build an Docker image'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              command: 'Build an image'
              dockerfile: "$(Build.SourcesDirectory)/mvc-minitwit/Dockerfile"
              imageName: '$(ImageName)'
              includeLatestTag: true
              useDefaultContext: false
              buildContext: '.'

          - task: Docker@1
            displayName: 'Push the Docker image to Dockerhub'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              command: 'Push an image'
              imageName: '$(ImageName)'
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))