# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  projectName: 'jokeren9/neutralsminitwit'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: test
              projects: "**/*HomeControllerTests/*.csproj"
          ##arguments: "--configuration $(BuildConfiguration)"
          - task: DockerCompose@0
            displayName: Build services
            inputs:
              action: Build services
              containerregistrytype: 'Container Registry' #how???
              dockerRegistryEndpoint: 'Docker Hub' #how?? 
              dockerComposeFile: "$(Build.SourcesDirectory)/mvc-minitwit/docker-compose.yml"
              projectName: $(projectName)
              qualifyImageNames: true
              additionalImageTags: $(Build.BuildId)

          - task: DockerCompose@0
            displayName: Push services
            inputs:
              action: Push services
              containerregistrytype: 'Container Registry' #how???
              dockerRegistryEndpoint: 'Docker Hub' #how?? 
              dockerComposeFile: "$(Build.SourcesDirectory)/mvc-minitwit/docker-compose.yml"
              projectName: $(projectName)
              qualifyImageNames: true
              additionalImageTags: $(Build.BuildId)

