server:

    http_listen_port: 9080
    grpc_listen_port: 0

positions:

    filename: /tmp/positions.yaml

clients:

    - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: system
    static_configs:
    - targets:
        - http://neutrals-minitwit.azurewebsites.net
      labels:
        job: varlogs
        __path__: /var/log/*.log
  - job_name: docker
    static_configs:
    - targets:
        - http://neutrals-minitwit.azurewebsites.net
      labels:
        job: varlogs
        __path__: /home/logfiles/*.log
  - job_name: docker2
    static_configs:
    - targets:
        - http://neutrals-minitwit.scm.azurewebsites.net
      labels:
        job: varlogs
        __path__: /home/logfiles/*.log